---
# tasks file for aws-ssm

- name: Install rpm file for Redhat Family (Amazon Linux, RHEL, and CentOS)
  become: yes
  become_user: root
  yum:
    name: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
    state: present

- name: Register to service
  become: yes
  become_user: root
  service:
    name: amazon-ssm-agent
    enabled: yes
    state: started